#ifndef ECU_CONFIG_CTRL_PRESS_ISOL_H_
#define ECU_CONFIG_CTRL_PRESS_ISOL_H_

#define USE_SRV_UI_SERIAL
#define USE_CTRL_PRESS_ISOL
#define USE_ED_RELAY
#define USE_SRV_SNS_AIR_TEMP
#define USE_ED_BMP
// #define USE_SRV_OS_TASK_SEQ
#define USE_SRV_OS_FREERTOS


#define ED_RELAY_REC (100 / SYS_TICK)   
#define ED_RELAY_OFFSET 5



#endif